{
 "title": "Performance Overview",
 "description": "A simple overview of instance performance.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "influxdb" },
   { "name": "RetentionPolicy", "label": "Data Age", "query": "SHOW RETENTION POLICIES" },
   {
    "name": "Host",
    "query": "SHOW TAG VALUES ON stig FROM \"sqlserver_server_properties\" WITH KEY = \"host\""
   },
   {
    "name": "Cores",
    "query": "SELECT last(\"cpu_count\") FROM \"$RetentionPolicy\".\"sqlserver_server_properties\" WHERE \"host\" =~ /$Host/"
   }
  ]
 },
 "panels": [
  { "title": "Server Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^(?i)$Host$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "cpu_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^(?i)$Host$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "server_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^(?i)$Host$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "db_online" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^(?i)$Host$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "db_offline" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^(?i)$Host$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "db_suspect" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^(?i)$Host$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "db_recovering" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^(?i)$Host$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "db_restoring" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^(?i)$Host$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "db_recoveryPending" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^(?i)$Host$/" }
     ]
    }
   ]
  },
  { "title": "Server Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "SQL Server Process",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_cpu",
     "select": [
      [
       { "params": [ "sqlserver_process_cpu" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Activity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_counter]]",
     "groupBy": [
      { "params": [ "server" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT non_negative_derivative(last(\"value\"), 1s) FROM \"$RetentionPolicy\".\"sqlserver_performance\" WHERE ((\"counter\" = 'Transactions/sec' AND \"instance\" =~ /^Total/ ) OR \"counter\" = 'SQL Re-Compilations/sec' OR \"counter\" = 'SQL Compilations/sec' OR \"counter\" = 'Batch Requests/sec') AND \"host\" =~ /^(?i)$Host$/ AND $timeFilter GROUP BY time($__interval), \"counter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "counter", "operator": "=", "value": "Transactions/sec" },
      { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" },
      { "condition": "OR", "key": "counter", "operator": "=", "value": "Batch Requests/sec" }
     ]
    },
    {
     "alias": "[[tag_counter]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "counter" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT max(\"value\") FROM \"$RetentionPolicy\".\"sqlserver_performance\" WHERE \"counter\" = 'User Connections'  AND \"host\" =~ /^(?i)$Host$/ AND $timeFilter GROUP BY time($interval), \"counter\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "counter", "operator": "=", "value": "Processes blocked" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^(?i)$Host$/" },
      { "condition": "OR", "key": "counter", "operator": "=", "value": "User Connections" }
     ]
    }
   ]
  },
  {
   "title": "Runnable Tasks",
   "type": "graph",
   "description": "Runnable task count per scheduler. Spikes in runnable tasks could mean CPU pressure.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Scheduler [[tag_scheduler_id]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "scheduler_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_schedulers",
     "select": [
      [
       { "params": [ "runnable_tasks_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "scheduler_id", "operator": "<>", "value": "*" }
     ]
    }
   ]
  },
  {
   "title": "Blocking and Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Deadlocks",
     "groupBy": [
      { "params": [ "server" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT non_negative_difference(last(\"value\")) FROM \"$RetentionPolicy\".\"sqlserver_performance\" WHERE \"counter\" = 'Number of Deadlocks/sec' AND \"host\" =~ /^(?i)$Host$/ AND $timeFilter GROUP BY time($__interval), \"counter\",\"instance\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "counter", "operator": "=", "value": "Transactions/sec" },
      { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" },
      { "condition": "OR", "key": "counter", "operator": "=", "value": "Batch Requests/sec" }
     ]
    },
    {
     "alias": "[[tag_counter]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "counter" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT max(\"value\") FROM \"$RetentionPolicy\".\"sqlserver_performance\" WHERE (\"counter\" = 'Processes blocked')  AND \"host\" =~ /^(?i)$Host$/ AND $timeFilter GROUP BY time($interval), \"counter\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "counter", "operator": "=", "value": "Processes blocked" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^(?i)$Host$/" },
      { "condition": "OR", "key": "counter", "operator": "=", "value": "User Connections" }
     ]
    },
    {
     "alias": "RunTImeErrorLog",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"ErrorCount\") FROM \"RunTimeErrorLog\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Workers per Scheduler",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Sched. [[tag_scheduler_id]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "scheduler_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_schedulers",
     "select": [
      [
       { "params": [ "active_workers_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "scheduler_id", "operator": "<>", "value": "*" }
     ]
    }
   ]
  },
  { "title": "Waits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Wait Stats - Total/Interval",
   "type": "graph",
   "description": "This graph shows the total accumulated wait for a given chunk of time.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_wait_type]]",
     "groupBy": [
      { "params": [ "wait_type" ], "type": "tag" }
     ],
     "measurement": "sqlserver_waitstats",
     "query": "SELECT  non_negative_derivative(last(\"wait_time_ms\"), $__interval) * 1.0\nFROM    \"$RetentionPolicy\".\"sqlserver_waitstats\"\nWHERE   \"host\" =~ /^$Host$/\n        AND $timeFilter\n        AND \"wait_type\" <> 'VDI_CLIENT_OTHER'\n        AND \"wait_type\" <> 'PWAIT_EXTENSIBILITY_CLEANUP_TASK'\nGROUP BY\n        time($__interval), \"wait_type\"",
     "select": [
      [
       { "params": [ "wait_time_ms" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "wait_category", "operator": "=~", "value": "/^$WaitCategory$/" }
     ]
    }
   ]
  },
  {
   "title": "Waits per Task",
   "type": "graph",
   "description": "This graph shows the average wait per task. This number is calculated by dividing total wait time for a given period of time, divided by the total number of tasks that have accumulated that wait type in that same period of time.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_wait_type]]",
     "groupBy": [
      { "params": [ "wait_type" ], "type": "tag" }
     ],
     "measurement": "sqlserver_waitstats",
     "query": "SELECT  non_negative_derivative(last(\"wait_time_ms\"), $__interval)/non_negative_derivative(last(\"waiting_tasks_count\"), $__interval)\nFROM    \"$RetentionPolicy\".\"sqlserver_waitstats\"\nWHERE   \"host\" =~ /^$Host$/\n        AND $timeFilter\n        AND \"wait_type\" <> 'VDI_CLIENT_OTHER'\n        AND \"wait_type\" <> 'PWAIT_EXTENSIBILITY_CLEANUP_TASK'\nGROUP BY time($__interval), \"wait_type\"",
     "select": [
      [
       { "params": [ "wait_time_ms" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "wait_category", "operator": "=~", "value": "/^$WaitCategory$/" }
     ]
    }
   ]
  },
  {
   "title": "Time Waiting (Per core, based on $Cores cores)",
   "type": "graph",
   "description": "This graph can be used to determine if an instance is CPU bound or if other factors are affecting throughput. \n\n - *Waiting for CPU* - Time spent waiting in line to get time on the CPU\n - *Waiting for Other Resources* - Time spent waiting on things other than the CPU, like waiting on disk, or waiting to write to a page in memory\n\nSome amount of waiting is fine and expected. This graph is broken out per core to help normalize the output for comparison across multiple instances.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Waiting for [[col]]/$__interval",
     "groupBy": [
      { "params": [ "wait_type" ], "type": "tag" }
     ],
     "measurement": "sqlserver_waitstats",
     "query": "SELECT  ((sum(\"signal_wait\") * 1.0)/$Cores) AS \"CPU\", (sum(\"resource_wait\") * 1.0) / $Cores AS \"Other Resources\"\nFROM (\nSELECT non_negative_derivative(last(\"signal_wait_time_ms\"),$__interval) AS \"signal_wait\", non_negative_derivative(last(\"resource_wait_ms\"),$__interval) AS \"resource_wait\"\nFROM    \"$RetentionPolicy\".\"sqlserver_waitstats\"\nWHERE   \"host\" =~ /^$Host$/\n        AND $timeFilter\n        AND \"wait_type\" <> 'VDI_CLIENT_OTHER'\n        AND \"wait_type\" <> 'PWAIT_EXTENSIBILITY_CLEANUP_TASK'\nGROUP BY\n        time($__interval), \"wait_type\"\n)\nWHERE\n$timeFilter\nGROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "wait_time_ms" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "wait_category", "operator": "=~", "value": "/^$WaitCategory$/" }
     ]
    }
   ]
  },
  { "title": "TempDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "TempDB Usage",
   "type": "graph",
   "description": "This shows both the free space in TempDB as well as the current amount of Version Store usage by RCSI. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_counter]]",
     "groupBy": [
      { "params": [ "server" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"$RetentionPolicy\".\"sqlserver_performance\" WHERE \"host\" =~ /^(?i)$Host$/ AND ( \"counter\" = 'Free Space in tempdb (KB)' OR \"counter\" = 'Version Store Size (KB)' ) AND $timeFilter GROUP BY \"server\", \"counter\", time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Free Space in tempdb (KB)" },
      { "condition": "OR", "key": "counter", "operator": "=", "value": "Version Store Size (KB)" }
     ]
    }
   ]
  },
  {
   "title": "Temp Tables",
   "type": "graph",
   "description": "Temp table and table variable statistics.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_counter]]",
     "groupBy": [
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "counter" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT max(\"value\") FROM \"$RetentionPolicy\".\"sqlserver_performance\" WHERE (\"counter\" = 'Active Temp Tables' OR \"counter\" = 'Temp Tables For Destruction') AND \"host\" =~ /^(?i)$Host$/ AND $timeFilter GROUP BY \"server\", \"counter\",time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "counter", "operator": "=", "value": "Active Temp Tables" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^(?i)$Host$/" }
     ]
    },
    {
     "alias": "Temp Tables Creation Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT non_negative_derivative(last(\"value\"), 1s) FROM \"$RetentionPolicy\".\"sqlserver_performance\" WHERE (\"counter\" = 'Temp Tables Creation Rate') AND \"host\" =~ /^(?i)$Host$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "counter", "operator": "=", "value": "Temp Tables Creation Rate" }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Memory Detail",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_clerk_type]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "clerk_type" ], "type": "tag" }
     ],
     "measurement": "sqlserver_memory_clerks",
     "select": [
      [
       { "params": [ "size_kb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^(?i)$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Performance",
   "type": "graph",
   "description": "*General*\nAll of the metrics here should be looked at over time and not in an isolated time period. There are general guidelines out there, but it makes most sense to just look for abnormal elevated values.\n\n- *Page Life Expectancy*: This is a measure of how long on average a *data* page can live in the buffer pool before being aged out, or evicted from memory pressure. \n- *Lazy Writes/sec*: Measure of how many dirty (altered) pages from the buffer pool are being flushed to disk per second.\n- *Page reads/sec*: Number of data pages being read *FROM* physical disk per second. Higher than normal values indicate increased memory pressure.\n- *Page writes/sec*: Similar to reads, this is the number of physical page writes per second. Higher than normal values indicate increased memory pressure.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Page life expectancy",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT last(\"value\") FROM \"$RetentionPolicy\".\"sqlserver_performance\" WHERE (\"counter\" = 'Page life expectancy' AND \"host\" =~ /^(?i)$Host$/) AND $timeFilter GROUP BY time($interval), \"instance\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "counter", "operator": "=", "value": "Page life expectancy" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^(?i)$Host$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:Buffer Manager" }
     ]
    },
    {
     "alias": "[[tag_counter]]",
     "groupBy": [
      { "params": [ "counter" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT non_negative_derivative(\"value\", 1s) FROM \"$RetentionPolicy\".\"sqlserver_performance\" WHERE \"host\" =~ /^(?i)$Host$/ AND ( \"counter\" = 'Page writes/sec' OR \"counter\" = 'Page reads/sec' OR \"counter\" = 'Lazy writes/sec' ) AND $timeFilter GROUP BY \"counter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Page writes/sec" }
     ]
    }
   ]
  },
  { "title": "IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Read Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "[[tag_instance]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sql_disk",
     "select": [
      [
       { "params": [ "Avg._Disk_sec/Read" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$__interval" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/(?i)^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "[[tag_instance]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sql_disk",
     "select": [
      [
       { "params": [ "Avg._Disk_sec/Write" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$__interval" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/(?i)^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Data Writes/Database",
   "type": "graph",
   "description": "This graph shows the amount of data written to each database during a given time period.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_database_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_database_io",
     "query": "SELECT non_negative_derivative(sum(\"write_bytes\"), $__interval) FROM \"$RetentionPolicy\".\"sqlserver_database_io\" WHERE (\"host\" =~ /(?i)^$Host$/) AND $timeFilter GROUP BY time($__interval), \"database_name\" fill(none) offset 1",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "$__interval" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/(?i)^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Data Reads/Database",
   "type": "graph",
   "description": "This graph shows the amount of data read from each database during a given time period.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_database_name]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "database_name" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sqlserver_database_io",
     "query": "SELECT non_negative_derivative(sum(\"read_bytes\"), $__interval) FROM \"$RetentionPolicy\".\"sqlserver_database_io\" WHERE (\"host\" =~ /(?i)^$Host$/) AND $timeFilter GROUP BY time($interval), \"database_name\" fill(previous) offset 1",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "$__interval" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/(?i)^$Host$/" }
     ]
    }
   ]
  },
  { "title": "Log Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Log Flushes",
   "type": "graph",
   "description": "This graph shows you general information on data being flushed from the log buffer to the transaction logs on disk. Increased values relate directly with increased workload.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "[[tag_counter]]",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "counter" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT non_negative_derivative(max(\"value\"), 1s) FROM \"$RetentionPolicy\".\"sqlserver_performance\" WHERE (\"counter\" = 'Log Bytes Flushed/sec' OR \"counter\" = 'Log Flushes/sec' ) AND \"instance\" = 'Total' AND \"host\" =~ /^(?i)$Host$/ AND $timeFilter GROUP BY time($__interval),\"counter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Log Bytes Flushed/sec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "counter", "operator": "=", "value": "Log Bytes Flushed/sec" },
      { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" }
     ],
     "timeField": "timestamp"
    }
   ]
  }
 ]
}